import { v4 as uuid } from "uuid";

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products = [
  {
    _id: uuid(),
    title: "TrustBasket Organic Vermicompost Fertilizer Manure for Plants(5KG)",
    imgUrl:"https://m.media-amazon.com/images/I/71iPA5LfB7L._AC_UL320_.jpg",
    price: 332,
    price_old:349,
    discount:5, 
    rating: 4.5,
    isBestSeller: true,
    isOutOfStock: false,
    categoryName: "Fertilizers",
  },
  {
    _id: uuid(),
    title: "TrustBasket Enriched Organic Earth Magic Potting Soil Fertilizer for Plants(5KG)",
    imgUrl:"https://m.media-amazon.com/images/I/61fUoGkNdHL._AC_UL320_.jpg",
    price: 950,
    price_old:1999,
    discount:52, 
    rating: 3.3,
    isBestSeller: true,
    isOutOfStock: false,
    categoryName: "Fertilizers",
  },
  {
    _id: uuid(),
    title: "Fieldstar 8-Litre Plastic Manual Sprayer for spraying fertilizers in Farms.",
    imgUrl:"https://m.media-amazon.com/images/I/61xnYxYWFsL._AC_UL320_.jpg",
    price: 950,
    price_old:1999,
    discount:52, 
    rating: 4.8,
    isBestSeller: false,
    isOutOfStock: false,
    categoryName: "Farming Tools",
  },
  {
    _id: uuid(),
    title: "FreshDcart Solar Soil Plant Care New 3 In 1 Water Moisture Soil Sensor.",
    imgUrl:"https://m.media-amazon.com/images/I/71WLLgqaUCL._AC_UL320_.jpg",
    price: 589,
    price_old:1010,
    discount:63, 
    rating: 3.8,
    isBestSeller: false,
    isOutOfStock: false,
    categoryName: "Electronic Devices",
  },
  {
    _id: uuid(),
    title: "WOLFGARTEN Steel Multi Star Culti-Weeder without Handle for Farms",
    imgUrl:"https://images-eu.ssl-images-amazon.com/images/I/61f0YRC22oL._AC_UL160_SR160,160_.jpg",
    price: 1270,
    price_old:2000,
    discount:37, 
    rating: 3.5,
    isBestSeller: false,
    isOutOfStock: false,
    categoryName: "Farming Tools",
  },
  {
    _id: uuid(),
    title: "FULLFILLBUY Farmer Safety Shoes, Paddy shoes, Agriculture Safety Shoes.",
    imgUrl:"https://m.media-amazon.com/images/I/31TYpYBcsoL._AC_UL320_.jpg",
    price: 1499,
    price_old:2000,
    discount:25, 
    rating: 2.5,
    isBestSeller: false,
    isOutOfStock: false,
    categoryName: "Safety Wearables",
  },
  {
    _id: uuid(),
    title: "Pick Ur Needs® Prime Metal 100w Rechargeable Waterproof Led Torch Light.",
    imgUrl:"https://m.media-amazon.com/images/I/61sXMk18mRL._AC_UL320_.jpg",
    price: 1799,
    price_old:2695,
    discount:33, 
    rating: 4.0,
    isBestSeller: false,
    isOutOfStock: false,
    categoryName: "Electronic Devices",
  },
  {
    _id: uuid(),
    title: "3M Polycarbonate Safety Goggles for Chemical Splash,Pack of 1,Clear",
    imgUrl:"https://m.media-amazon.com/images/I/51tkdrj3cAL._AC_UL320_.jpg",
    price: 110,
    price_old:115,
    discount:4, 
    rating: 2.1,
    isBestSeller: false,
    isOutOfStock: true,
    categoryName: "Safety Wearables",
  },
];
